[build]
  base = "."
  publish = "dist/public"
  command = "npm run build"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
